USE bdtransmilenioproyecto;

ALTER TABLE TRONCALES ADD
CONSTRAINT TRON_PK_ID_TRONCAL PRIMARY KEY(ID_TRONCAL);


ALTER TABLE ESTACIONES ADD
CONSTRAINT ESTA_PK_NOM_ESTA PRIMARY KEY(NOMBRE_ESTACION),
CONSTRAINT ESTA_FK_TRONCA_IDTRON FOREIGN KEY (ID_TRONCAL) REFERENCES TRONCALES (ID_TRONCAL),
CONSTRAINT ESTA_CK_TIPEST CHECK (TIPO_ESTACION IN ('T','A','U')),
CONSTRAINT ESTA_CK_TIPCABE CHECK (TIPO_CABECERA IN ('P','E'));

ALTER TABLE RUTAS ADD
CONSTRAINT RUT_PK_ID_RUTA PRIMARY KEY(ID_RUTA),
CONSTRAINT RUT_CK_TIPBUS CHECK (TIPO_BUS IN ('T','A','U'));

ALTER TABLE ESTACIONES_RUTAS ADD
CONSTRAINT ESTARUT_PK_ID_ESTRUT PRIMARY KEY(ID_RUTA,NOMBRE_ESTACION),
CONSTRAINT ESTARUT_FK_RUTAS_IDRUT FOREIGN KEY (ID_RUTA) REFERENCES RUTAS (ID_RUTA),
CONSTRAINT ESTARUT_FK__EST_IDESTA FOREIGN KEY (NOMBRE_ESTACION) REFERENCES ESTACIONES (NOMBRE_ESTACION);

ALTER TABLE HORARIOS_RUTAS ADD
CONSTRAINT HORARRUT_PK_ID_HORAR PRIMARY KEY(ID_HORARIO,ID_RUTA),
CONSTRAINT HORARRUT_FK_RUTAS_IDRUT FOREIGN KEY (ID_RUTA) REFERENCES RUTAS (ID_RUTA),
CONSTRAINT HORARRUT_CK_TIPHORA CHECK (ID_HORARIO IN ('L-V','S','DF')),
CONSTRAINT HORARRUT_CK_DIAINI check (DIA_INICIO between 1 and 7),
CONSTRAINT HORARRUT_CK_DIAINIVAL check (DIA_INICIO=1 OR DIA_INICIO=6),
CONSTRAINT HORARRUT_CK_DIAFIN check (DIA_FIN between 1 and 7),
CONSTRAINT HORARRUT_CK_DIAFINVAL check (DIA_FIN=5);