package models.entity;
// Generated 03-abr-2019 21:43:08 by Hibernate Tools 4.3.1



/**
 * EstacionesRutasId generated by hbm2java
 */
public class EstacionesRutasId  implements java.io.Serializable {


     private String idRuta;
     private String nombreEstacion;

    public EstacionesRutasId() {
    }

    public EstacionesRutasId(String idRuta, String nombreEstacion) {
       this.idRuta = idRuta;
       this.nombreEstacion = nombreEstacion;
    }
   
    public String getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(String idRuta) {
        this.idRuta = idRuta;
    }
    public String getNombreEstacion() {
        return this.nombreEstacion;
    }
    
    public void setNombreEstacion(String nombreEstacion) {
        this.nombreEstacion = nombreEstacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstacionesRutasId) ) return false;
		 EstacionesRutasId castOther = ( EstacionesRutasId ) other; 
         
		 return ( (this.getIdRuta()==castOther.getIdRuta()) || ( this.getIdRuta()!=null && castOther.getIdRuta()!=null && this.getIdRuta().equals(castOther.getIdRuta()) ) )
 && ( (this.getNombreEstacion()==castOther.getNombreEstacion()) || ( this.getNombreEstacion()!=null && castOther.getNombreEstacion()!=null && this.getNombreEstacion().equals(castOther.getNombreEstacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRuta() == null ? 0 : this.getIdRuta().hashCode() );
         result = 37 * result + ( getNombreEstacion() == null ? 0 : this.getNombreEstacion().hashCode() );
         return result;
   }   


}


