package models.entity;
// Generated 03-abr-2019 21:43:08 by Hibernate Tools 4.3.1



/**
 * EstacionesRutas generated by hbm2java
 */
public class EstacionesRutas  implements java.io.Serializable {


     private EstacionesRutasId id;
     private Estaciones estaciones;
     private Rutas rutas;
     private int ordenRuta;

    public EstacionesRutas() {
        estaciones=new Estaciones();
        rutas=new Rutas();
    }

    public EstacionesRutas(EstacionesRutasId id, Estaciones estaciones, Rutas rutas, int ordenRuta) {
       this.id = id;
       this.estaciones = estaciones;
       this.rutas = rutas;
       this.ordenRuta = ordenRuta;
    }
   
    public EstacionesRutasId getId() {
        return this.id;
    }
    
    public void setId(EstacionesRutasId id) {
        this.id = id;
    }
    public Estaciones getEstaciones() {
        return this.estaciones;
    }
    
    public void setEstaciones(Estaciones estaciones) {
        this.estaciones = estaciones;
    }
    public Rutas getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Rutas rutas) {
        this.rutas = rutas;
    }
    public int getOrdenRuta() {
        return this.ordenRuta;
    }
    
    public void setOrdenRuta(int ordenRuta) {
        this.ordenRuta = ordenRuta;
    }




}


