package models.entity;
// Generated 03-abr-2019 21:43:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private String nombreEstacion;
     private Troncales troncales;
     private String tipoEstacion;
     private String tipoCabecera;
     private Set<EstacionesRutas> estacionesRutases = new HashSet(0);

    public Estaciones() {
        troncales=new Troncales();
    }

	
    public Estaciones(String nombreEstacion, String tipoEstacion) {
        this.nombreEstacion = nombreEstacion;
        this.tipoEstacion = tipoEstacion;
    }
    public Estaciones(String nombreEstacion, Troncales troncales, String tipoEstacion, String tipoCabecera, Set estacionesRutases) {
       this.nombreEstacion = nombreEstacion;
       this.troncales = troncales;
       this.tipoEstacion = tipoEstacion;
       this.tipoCabecera = tipoCabecera;
       this.estacionesRutases = estacionesRutases;
    }
   
    public String getNombreEstacion() {
        return this.nombreEstacion;
    }
    
    public void setNombreEstacion(String nombreEstacion) {
        this.nombreEstacion = nombreEstacion;
    }
    public Troncales getTroncales() {
        return this.troncales;
    }
    
    public void setTroncales(Troncales troncales) {
        this.troncales = troncales;
    }
    public String getTipoEstacion() {
        return this.tipoEstacion;
    }
    
    public void setTipoEstacion(String tipoEstacion) {
        this.tipoEstacion = tipoEstacion;
    }
    public String getTipoCabecera() {
        return this.tipoCabecera;
    }
    
    public void setTipoCabecera(String tipoCabecera) {
        this.tipoCabecera = tipoCabecera;
    }
    public Set<EstacionesRutas> getEstacionesRutases() {
        return this.estacionesRutases;
    }
    
    public void setEstacionesRutases(Set<EstacionesRutas> estacionesRutases) {
        this.estacionesRutases = estacionesRutases;
    }




}


