package models.entity;
// Generated 02-abr-2019 12:32:39 by Hibernate Tools 4.3.1



/**
 * EstacionesRutasId generated by hbm2java
 */
public class EstacionesRutasId  implements java.io.Serializable {


     private String idRuta;
     private int idEstacion;

    public EstacionesRutasId() {
    }

    public EstacionesRutasId(String idRuta, int idEstacion) {
       this.idRuta = idRuta;
       this.idEstacion = idEstacion;
    }
   
    public String getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(String idRuta) {
        this.idRuta = idRuta;
    }
    public int getIdEstacion() {
        return this.idEstacion;
    }
    
    public void setIdEstacion(int idEstacion) {
        this.idEstacion = idEstacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstacionesRutasId) ) return false;
		 EstacionesRutasId castOther = ( EstacionesRutasId ) other; 
         
		 return ( (this.getIdRuta()==castOther.getIdRuta()) || ( this.getIdRuta()!=null && castOther.getIdRuta()!=null && this.getIdRuta().equals(castOther.getIdRuta()) ) )
 && (this.getIdEstacion()==castOther.getIdEstacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRuta() == null ? 0 : this.getIdRuta().hashCode() );
         result = 37 * result + this.getIdEstacion();
         return result;
   }   


}


