package models.entity;
// Generated 03-abr-2019 21:43:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HorariosRutas generated by hbm2java
 */
public class HorariosRutas  implements java.io.Serializable {


     private HorariosRutasId id;
     private Rutas rutas;
     private int diaInicio;
     private Integer diaFin;
     private Date horaInicio;
     private Date horaFin;

    public HorariosRutas() {
    }

	
    public HorariosRutas(HorariosRutasId id, Rutas rutas, int diaInicio, Date horaInicio, Date horaFin) {
        this.id = id;
        this.rutas = rutas;
        this.diaInicio = diaInicio;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
    }
    public HorariosRutas(HorariosRutasId id, Rutas rutas, int diaInicio, Integer diaFin, Date horaInicio, Date horaFin) {
       this.id = id;
       this.rutas = rutas;
       this.diaInicio = diaInicio;
       this.diaFin = diaFin;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
    public HorariosRutasId getId() {
        return this.id;
    }
    
    public void setId(HorariosRutasId id) {
        this.id = id;
    }
    public Rutas getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Rutas rutas) {
        this.rutas = rutas;
    }
    public int getDiaInicio() {
        return this.diaInicio;
    }
    
    public void setDiaInicio(int diaInicio) {
        this.diaInicio = diaInicio;
    }
    public Integer getDiaFin() {
        return this.diaFin;
    }
    
    public void setDiaFin(Integer diaFin) {
        this.diaFin = diaFin;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


