package models.entity;
// Generated 02-abr-2019 12:32:39 by Hibernate Tools 4.3.1



/**
 * HorariosRutasId generated by hbm2java
 */
public class HorariosRutasId  implements java.io.Serializable {


     private String idHorario;
     private String idRuta;

    public HorariosRutasId() {
    }

    public HorariosRutasId(String idHorario, String idRuta) {
       this.idHorario = idHorario;
       this.idRuta = idRuta;
    }
   
    public String getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(String idHorario) {
        this.idHorario = idHorario;
    }
    public String getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(String idRuta) {
        this.idRuta = idRuta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HorariosRutasId) ) return false;
		 HorariosRutasId castOther = ( HorariosRutasId ) other; 
         
		 return ( (this.getIdHorario()==castOther.getIdHorario()) || ( this.getIdHorario()!=null && castOther.getIdHorario()!=null && this.getIdHorario().equals(castOther.getIdHorario()) ) )
 && ( (this.getIdRuta()==castOther.getIdRuta()) || ( this.getIdRuta()!=null && castOther.getIdRuta()!=null && this.getIdRuta().equals(castOther.getIdRuta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdHorario() == null ? 0 : this.getIdHorario().hashCode() );
         result = 37 * result + ( getIdRuta() == null ? 0 : this.getIdRuta().hashCode() );
         return result;
   }   


}


