package models.entity;
// Generated 02-abr-2019 12:32:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rutas generated by hbm2java
 */
public class Rutas  implements java.io.Serializable {


     private String idRuta;
     private String nombreRuta;
     private String tipoBus;
     private Set<EstacionesRutas> estacionesRutases = new HashSet(0);
     private Set<HorariosRutas> horariosRutases = new HashSet(0);

    public Rutas() {
    }

	
    public Rutas(String idRuta, String tipoBus) {
        this.idRuta = idRuta;
        this.tipoBus = tipoBus;
    }
    public Rutas(String idRuta, String nombreRuta, String tipoBus, Set<EstacionesRutas> estacionesRutases, Set<HorariosRutas> horariosRutases) {
       this.idRuta = idRuta;
       this.nombreRuta = nombreRuta;
       this.tipoBus = tipoBus;
       this.estacionesRutases = estacionesRutases;
       this.horariosRutases = horariosRutases;
    }
   
    public String getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(String idRuta) {
        this.idRuta = idRuta;
    }
    public String getNombreRuta() {
        return this.nombreRuta;
    }
    
    public void setNombreRuta(String nombreRuta) {
        this.nombreRuta = nombreRuta;
    }
    public String getTipoBus() {
        return this.tipoBus;
    }
    
    public void setTipoBus(String tipoBus) {
        this.tipoBus = tipoBus;
    }
    public Set<EstacionesRutas> getEstacionesRutases() {
        return this.estacionesRutases;
    }
    
    public void setEstacionesRutases(Set<EstacionesRutas> estacionesRutases) {
        this.estacionesRutases = estacionesRutases;
    }
    public Set<HorariosRutas> getHorariosRutases() {
        return this.horariosRutases;
    }
    
    public void setHorariosRutases(Set<HorariosRutas> horariosRutases) {
        this.horariosRutases = horariosRutases;
    }




}


