package models.entity;
// Generated 02-abr-2019 12:32:39 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Troncales generated by hbm2java
 */
public class Troncales  implements java.io.Serializable {


     private String idTroncal;
     private String nombreTroncal;
     private BigDecimal longitudTroncal;
     private String unidadesLongitud;
     private Set estacioneses = new HashSet(0);

    public Troncales() {
    }

	
    public Troncales(String idTroncal, String nombreTroncal, BigDecimal longitudTroncal, String unidadesLongitud) {
        this.idTroncal = idTroncal;
        this.nombreTroncal = nombreTroncal;
        this.longitudTroncal = longitudTroncal;
        this.unidadesLongitud = unidadesLongitud;
    }
    public Troncales(String idTroncal, String nombreTroncal, BigDecimal longitudTroncal, String unidadesLongitud, Set estacioneses) {
       this.idTroncal = idTroncal;
       this.nombreTroncal = nombreTroncal;
       this.longitudTroncal = longitudTroncal;
       this.unidadesLongitud = unidadesLongitud;
       this.estacioneses = estacioneses;
    }
   
    public String getIdTroncal() {
        return this.idTroncal;
    }
    
    public void setIdTroncal(String idTroncal) {
        this.idTroncal = idTroncal;
    }
    public String getNombreTroncal() {
        return this.nombreTroncal;
    }
    
    public void setNombreTroncal(String nombreTroncal) {
        this.nombreTroncal = nombreTroncal;
    }
    public BigDecimal getLongitudTroncal() {
        return this.longitudTroncal;
    }
    
    public void setLongitudTroncal(BigDecimal longitudTroncal) {
        this.longitudTroncal = longitudTroncal;
    }
    public String getUnidadesLongitud() {
        return this.unidadesLongitud;
    }
    
    public void setUnidadesLongitud(String unidadesLongitud) {
        this.unidadesLongitud = unidadesLongitud;
    }
    public Set getEstacioneses() {
        return this.estacioneses;
    }
    
    public void setEstacioneses(Set estacioneses) {
        this.estacioneses = estacioneses;
    }




}


